export const pt = {
  "loginTitle": "Bem-vindo de volta!",
  "emailLabel": "E-mail",
  "passwordLabel": "Senha",
  "loginButton": "Entrar",
  "noAccount": "Não tem uma conta ainda?",
  "registerHere": "Registre-se aqui!",
  "registerTitle": "Crie sua conta",
  "nameLabel": "Nome",
  "confirmPasswordLabel": "Confirmar Senha",
  "registerButton": "Registrar",
  "profileSetupTitle": "Configure seu Perfil de Saúde",
  "ageLabel": "Idade",
  "weightLabel": "Peso (kg)",
  "heightLabel": "Altura (cm)",
  "genderLabel": "Sexo",
  "dietaryPreferencesLabel": "Preferências Alimentares (opcional)",
  "healthConditionsTitle": "Condições de Saúde (selecione todas que se aplicam)",
  "diabetes": "Diabetes",
  "hypertension": "Hipertensão",
  "cholesterol": "Colesterol alto / Triglicerídeos",
  "obesity": "Obesidade",
  "finishButton": "Finalizar",
  "cameraTitle": "Analisar Alimento",
  "cameraInstruction": "Tire uma foto do seu alimento",
  "cameraButton": "Câmera",
  "galleryButton": "Galeria",
  "settingsButton": "Configurações",
  "analysisResultTitle": "Resultado da Análise",
  "foodLabel": "Alimento",
  "nutritionalInfo": "Informações Nutricionais",
  "calories": "Calorias",
  "carbs": "Carboidratos",
  "sugar": "Açúcar",
  "fat": "Gordura",
  "sodium": "Sódio",
  "protein": "Proteína",
  "alertTitle": "Alerta de Saúde",
  "substitutesTitle": "Sugestões de Substitutos",
  "newPhotoButton": "Nova Foto",
  "saveAnalysisButton": "Salvar Análise",
  "settingsTitle": "Configurações",
  "languageLabel": "Idioma",
  "male": "Masculino",
  "female": "Feminino",
  "other": "Outro",
  "analyzing": "Analisando sua foto...",
  "alert_GREEN": "Alimento Permitido",
  "alert_YELLOW": "Permitido com Moderação",
  "alert_RED": "Não Recomendado",
  "error_title": "Erro",
  "error_message": "Não foi possível analisar a imagem. Por favor, tente novamente com uma foto mais nítida.",
  "ok": "OK",
  "error_password_mismatch": "As senhas não coincidem.",
  "error_password_complexity": "A senha deve conter no mínimo 4 letras ou 4 números.",
  "error_min_age": "Você deve ter no mínimo 18 anos para se cadastrar.",
  "motivationalQuote_good": "Parabéns! Você está no caminho certo!",
  "motivationalQuote_keepGoing": "Continue focando, você consegue atingir suas metas hoje!",
  "userProfileTitle": "Olá, Usuário!",
  "userProfileSubtitle": "Pronto para sua meta de hoje?",
  "dailyProgressTitle": "Progresso Diário",
  "todayHistoryTitle": "Histórico de Hoje"
};

export const en = {
  "loginTitle": "Welcome back!",
  "emailLabel": "Email",
  "passwordLabel": "Password",
  "loginButton": "Log In",
  "noAccount": "Don't have an account yet?",
  "registerHere": "Register here!",
  "registerTitle": "Create your account",
  "nameLabel": "Name",
  "confirmPasswordLabel": "Confirm Password",
  "registerButton": "Register",
  "profileSetupTitle": "Set up your Health Profile",
  "ageLabel": "Age",
  "weightLabel": "Weight (kg)",
  "heightLabel": "Height (cm)",
  "genderLabel": "Gender",
  "dietaryPreferencesLabel": "Dietary Preferences (optional)",
  "healthConditionsTitle": "Health Conditions (select all that apply)",
  "diabetes": "Diabetes",
  "hypertension": "Hypertension",
  "cholesterol": "High cholesterol / Triglycerides",
  "obesity": "Obesity",
  "finishButton": "Finish",
  "cameraTitle": "Analyze Food",
  "cameraInstruction": "Take a photo of your food",
  "cameraButton": "Camera",
  "galleryButton": "Gallery",
  "settingsButton": "Settings",
  "analysisResultTitle": "Analysis Result",
  "foodLabel": "Food",
  "nutritionalInfo": "Nutritional Information",
  "calories": "Calories",
  "carbs": "Carbohydrates",
  "sugar": "Sugar",
  "fat": "Fat",
  "sodium": "Sodium",
  "protein": "Protein",
  "alertTitle": "Health Alert",
  "substitutesTitle": "Substitute Suggestions",
  "newPhotoButton": "New Photo",
  "saveAnalysisButton": "Save Analysis",
  "settingsTitle": "Settings",
  "languageLabel": "Language",
  "male": "Male",
  "female": "Female",
  "other": "Other",
  "analyzing": "Analyzing your photo...",
  "alert_GREEN": "Permitted Food",
  "alert_YELLOW": "Permitted with Moderation",
  "alert_RED": "Not Recommended",
  "error_title": "Error",
  "error_message": "Could not analyze the image. Please try again with a clearer photo.",
  "ok": "OK",
  "error_password_mismatch": "Passwords do not match.",
  "error_password_complexity": "Password must contain at least 4 letters or 4 numbers.",
  "error_min_age": "You must be at least 18 years old to register.",
  "motivationalQuote_good": "Congratulations! You are on the right track!",
  "motivationalQuote_keepGoing": "Keep focusing, you can reach your goals today!",
  "userProfileTitle": "Hello, User!",
  "userProfileSubtitle": "Ready for today's goal?",
  "dailyProgressTitle": "Daily Progress",
  "todayHistoryTitle": "Today's History"
};

export const es = {
  "loginTitle": "¡Bienvenido de nuevo!",
  "emailLabel": "Correo electrónico",
  "passwordLabel": "Contraseña",
  "loginButton": "Iniciar sesión",
  "noAccount": "¿Aún no tienes una cuenta?",
  "registerHere": "¡Regístrate aquí!",
  "registerTitle": "Crea tu cuenta",
  "nameLabel": "Nombre",
  "confirmPasswordLabel": "Confirmar Contraseña",
  "registerButton": "Registrarse",
  "profileSetupTitle": "Configura tu Perfil de Salud",
  "ageLabel": "Edad",
  "weightLabel": "Peso (kg)",
  "heightLabel": "Altura (cm)",
  "genderLabel": "Género",
  "dietaryPreferencesLabel": "Preferencias Alimentarias (opcional)",
  "healthConditionsTitle": "Condiciones de Salud (selecciona todas las que apliquen)",
  "diabetes": "Diabetes",
  "hypertension": "Hipertensión",
  "cholesterol": "Colesterol alto / Triglicéridos",
  "obesity": "Obesidad",
  "finishButton": "Finalizar",
  "cameraTitle": "Analizar Alimento",
  "cameraInstruction": "Toma una foto de tu comida",
  "cameraButton": "Cámara",
  "galleryButton": "Galería",
  "settingsButton": "Configuración",
  "analysisResultTitle": "Resultado del Análisis",
  "foodLabel": "Alimento",
  "nutritionalInfo": "Información Nutricional",
  "calories": "Calorías",
  "carbs": "Carbohidratos",
  "sugar": "Azúcar",
  "fat": "Grasa",
  "sodium": "Sodio",
  "protein": "Proteína",
  "alertTitle": "Alerta de Salud",
  "substitutesTitle": "Sugerencias de Sustitutos",
  "newPhotoButton": "Nueva Foto",
  "saveAnalysisButton": "Guardar Análisis",
  "settingsTitle": "Configuración",
  "languageLabel": "Idioma",
  "male": "Masculino",
  "female": "Femenino",
  "other": "Otro",
  "analyzing": "Analizando tu foto...",
  "alert_GREEN": "Alimento Permitido",
  "alert_YELLOW": "Permitido con Moderación",
  "alert_RED": "No Recomendado",
  "error_title": "Error",
  "error_message": "No se pudo analizar la imagen. Por favor, inténtalo de nuevo con una foto más nítida.",
  "ok": "OK",
  "error_password_mismatch": "Las contraseñas no coinciden.",
  "error_password_complexity": "La contraseña debe contener al menos 4 letras o 4 números.",
  "error_min_age": "Debes tener al menos 18 años para registrarte.",
  "motivationalQuote_good": "¡Felicidades! ¡Estás en el camino correcto!",
  "motivationalQuote_keepGoing": "¡Sigue concentrado, puedes alcanzar tus metas hoy!",
  "userProfileTitle": "¡Hola, Usuario!",
  "userProfileSubtitle": "¿Listo para tu meta de hoy?",
  "dailyProgressTitle": "Progreso Diario",
  "todayHistoryTitle": "Historial de Hoy"
};

export const fr = {
  "loginTitle": "Content de vous revoir!",
  "emailLabel": "E-mail",
  "passwordLabel": "Mot de passe",
  "loginButton": "Se connecter",
  "noAccount": "Vous n'avez pas encore de compte ?",
  "registerHere": "Inscrivez-vous ici !",
  "registerTitle": "Créez votre compte",
  "nameLabel": "Nom",
  "confirmPasswordLabel": "Confirmez le mot de passe",
  "registerButton": "S'inscrire",
  "profileSetupTitle": "Configurez votre profil de santé",
  "ageLabel": "Âge",
  "weightLabel": "Poids (kg)",
  "heightLabel": "Taille (cm)",
  "genderLabel": "Genre",
  "dietaryPreferencesLabel": "Préférences alimentaires (facultatif)",
  "healthConditionsTitle": "Conditions de santé (sélectionnez tout ce qui s'applique)",
  "diabetes": "Diabète",
  "hypertension": "Hypertension",
  "cholesterol": "Cholestérol élevé / Triglycérides",
  "obesity": "Obésité",
  "finishButton": "Terminer",
  "cameraTitle": "Analyser un aliment",
  "cameraInstruction": "Prenez une photo de votre nourriture",
  "cameraButton": "Appareil photo",
  "galleryButton": "Galerie",
  "settingsButton": "Paramètres",
  "analysisResultTitle": "Résultat de l'analyse",
  "foodLabel": "Aliment",
  "nutritionalInfo": "Informations nutritionnelles",
  "calories": "Calories",
  "carbs": "Glucides",
  "sugar": "Sucre",
  "fat": "Graisse",
  "sodium": "Sodium",
  "protein": "Protéine",
  "alertTitle": "Alerte santé",
  "substitutesTitle": "Suggestions de substituts",
  "newPhotoButton": "Nouvelle Photo",
  "saveAnalysisButton": "Sauvegarder l'analyse",
  "settingsTitle": "Paramètres",
  "languageLabel": "Langue",
  "male": "Homme",
  "female": "Femme",
  "other": "Autre",
  "analyzing": "Analyse de votre photo...",
  "alert_GREEN": "Aliment autorisé",
  "alert_YELLOW": "Autorisé avec modération",
  "alert_RED": "Non recommandé",
  "error_title": "Erreur",
  "error_message": "Impossible d'analyser l'image. Veuillez réessayer avec une photo plus nette.",
  "ok": "OK",
  "error_password_mismatch": "Les mots de passe ne correspondent pas.",
  "error_password_complexity": "Le mot de passe doit contenir au moins 4 lettres ou 4 chiffres.",
  "error_min_age": "Vous devez avoir au moins 18 ans pour vous inscrire.",
  "motivationalQuote_good": "Félicitations ! Vous êtes sur la bonne voie !",
  "motivationalQuote_keepGoing": "Restez concentré, vous pouvez atteindre vos objectifs aujourd'hui !",
  "userProfileTitle": "Bonjour, Utilisateur !",
  "userProfileSubtitle": "Prêt pour votre objectif d'aujourd'hui ?",
  "dailyProgressTitle": "Progrès quotidien",
  "todayHistoryTitle": "Historique d'aujourd'hui"
};

export const ja = {
  "loginTitle": "おかえりなさい！",
  "emailLabel": "Eメール",
  "passwordLabel": "パスワード",
  "loginButton": "ログイン",
  "noAccount": "まだアカウントをお持ちではありませんか？",
  "registerHere": "こちらで登録！",
  "registerTitle": "アカウントを作成",
  "nameLabel": "名前",
  "confirmPasswordLabel": "パスワードを確認",
  "registerButton": "登録",
  "profileSetupTitle": "健康プロフィールを設定",
  "ageLabel": "年齢",
  "weightLabel": "体重 (kg)",
  "heightLabel": "身長 (cm)",
  "genderLabel": "性別",
  "dietaryPreferencesLabel": "食事の好み (任意)",
  "healthConditionsTitle": "健康状態 (当てはまるものをすべて選択)",
  "diabetes": "糖尿病",
  "hypertension": "高血圧",
  "cholesterol": "高コレステロール / 中性脂肪",
  "obesity": "肥満",
  "finishButton": "完了",
  "cameraTitle": "食品を分析",
  "cameraInstruction": "食べ物の写真を撮ってください",
  "cameraButton": "カメラ",
  "galleryButton": "ギャラリー",
  "settingsButton": "設定",
  "analysisResultTitle": "分析結果",
  "foodLabel": "食品",
  "nutritionalInfo": "栄養情報",
  "calories": "カロリー",
  "carbs": "炭水化物",
  "sugar": "砂糖",
  "fat": "脂肪",
  "sodium": "ナトリウム",
  "protein": "タンパク質",
  "alertTitle": "健康アラート",
  "substitutesTitle": "代替品の提案",
  "newPhotoButton": "新しい写真",
  "saveAnalysisButton": "分析を保存",
  "settingsTitle": "設定",
  "languageLabel": "言語",
  "male": "男性",
  "female": "女性",
  "other": "その他",
  "analyzing": "写真を分析中...",
  "alert_GREEN": "許可された食品",
  "alert_YELLOW": "適度に許可",
  "alert_RED": "推奨されません",
  "error_title": "エラー",
  "error_message": "画像を分析できませんでした。もっと鮮明な写真で再試行してください。",
  "ok": "OK",
  "error_password_mismatch": "パスワードが一致しません。",
  "error_password_complexity": "パスワードには少なくとも4文字の英字または4桁の数字を含める必要があります。",
  "error_min_age": "登録するには18歳以上である必要があります。",
  "motivationalQuote_good": "おめでとうございます！順調です！",
  "motivationalQuote_keepGoing": "集中し続けて、今日の目標を達成できます！",
  "userProfileTitle": "こんにちは、ユーザーさん！",
  "userProfileSubtitle": "今日の目標の準備はできましたか？",
  "dailyProgressTitle": "毎日の進捗",
  "todayHistoryTitle": "今日の履歴"
};

export const zh = {
  "loginTitle": "欢迎回来！",
  "emailLabel": "电子邮件",
  "passwordLabel": "密码",
  "loginButton": "登录",
  "noAccount": "还没有账户吗？",
  "registerHere": "在这里注册！",
  "registerTitle": "创建您的帐户",
  "nameLabel": "姓名",
  "confirmPasswordLabel": "确认密码",
  "registerButton": "注册",
  "profileSetupTitle": "设置您的健康档案",
  "ageLabel": "年龄",
  "weightLabel": "体重 (kg)",
  "heightLabel": "身高 (cm)",
  "genderLabel": "性别",
  "dietaryPreferencesLabel": "饮食偏好 (可选)",
  "healthConditionsTitle": "健康状况 (选择所有适用项)",
  "diabetes": "糖尿病",
  "hypertension": "高血压",
  "cholesterol": "高胆固醇 / 甘油三酯",
  "obesity": "肥胖",
  "finishButton": "完成",
  "cameraTitle": "分析食物",
  "cameraInstruction": "拍一张你的食物照片",
  "cameraButton": "相机",
  "galleryButton": "相册",
  "settingsButton": "设置",
  "analysisResultTitle": "分析结果",
  "foodLabel": "食物",
  "nutritionalInfo": "营养信息",
  "calories": "卡路里",
  "carbs": "碳水化合物",
  "sugar": "糖",
  "fat": "脂肪",
  "sodium": "钠",
  "protein": "蛋白质",
  "alertTitle": "健康警报",
  "substitutesTitle": "替代建议",
  "newPhotoButton": "新照片",
  "saveAnalysisButton": "保存分析",
  "settingsTitle": "设置",
  "languageLabel": "语言",
  "male": "男性",
  "female": "女性",
  "other": "其他",
  "analyzing": "正在分析您的照片...",
  "alert_GREEN": "允许的食物",
  "alert_YELLOW": "适度允许",
  "alert_RED": "不推荐",
  "error_title": "错误",
  "error_message": "无法分析图像。请用更清晰的照片重试。",
  "ok": "好的",
  "error_password_mismatch": "密码不匹配。",
  "error_password_complexity": "密码必须包含至少4个字母或4个数字。",
  "error_min_age": "您必须年满18岁才能注册。",
  "motivationalQuote_good": "恭喜！您走在正确的道路上！",
  "motivationalQuote_keepGoing": "继续专注，今天您能实现目标！",
  "userProfileTitle": "你好，用户！",
  "userProfileSubtitle": "准备好今天的目标了吗？",
  "dailyProgressTitle": "每日进度",
  "todayHistoryTitle": "今日历史"
};

export const ar = {
  "loginTitle": "مرحباً بعودتك!",
  "emailLabel": "البريد الإلكتروني",
  "passwordLabel": "كلمة المرور",
  "loginButton": "تسجيل الدخول",
  "noAccount": "ليس لديك حساب بعد؟",
  "registerHere": "سجل هنا!",
  "registerTitle": "أنشئ حسابك",
  "nameLabel": "الاسم",
  "confirmPasswordLabel": "تأكيد كلمة المرور",
  "registerButton": "تسجيل",
  "profileSetupTitle": "قم بإعداد ملفك الصحي",
  "ageLabel": "العمر",
  "weightLabel": "الوزن (كجم)",
  "heightLabel": "الطول (سم)",
  "genderLabel": "الجنس",
  "dietaryPreferencesLabel": "التفضيلات الغذائية (اختياري)",
  "healthConditionsTitle": "الحالات الصحية (اختر كل ما ينطبق)",
  "diabetes": "السكري",
  "hypertension": "ارتفاع ضغط الدم",
  "cholesterol": "ارتفاع الكوليسترول / الدهون الثلاثية",
  "obesity": "السمنة",
  "finishButton": "إنهاء",
  "cameraTitle": "تحليل الطعام",
  "cameraInstruction": "التقط صورة لطعامك",
  "cameraButton": "الكاميرا",
  "galleryButton": "المعرض",
  "settingsButton": "الإعدادات",
  "analysisResultTitle": "نتيجة التحليل",
  "foodLabel": "الطعام",
  "nutritionalInfo": "المعلومات الغذائية",
  "calories": "السعرات الحرارية",
  "carbs": "الكربوهيدرات",
  "sugar": "السكر",
  "fat": "الدهون",
  "sodium": "الصوديوم",
  "protein": "البروتين",
  "alertTitle": "تنبيه صحي",
  "substitutesTitle": "اقتراحات بديلة",
  "newPhotoButton": "صورة جديدة",
  "saveAnalysisButton": "حفظ التحليل",
  "settingsTitle": "الإعدادات",
  "languageLabel": "اللغة",
  "male": "ذكر",
  "female": "أنثى",
  "other": "آخر",
  "analyzing": "جاري تحليل صورتك...",
  "alert_GREEN": "طعام مسموح به",
  "alert_YELLOW": "مسموح به باعتدال",
  "alert_RED": "غير موصى به",
  "error_title": "خطأ",
  "error_message": "تعذر تحليل الصورة. يرجى المحاولة مرة أخرى بصورة أوضح.",
  "ok": "موافق",
  "error_password_mismatch": "كلمات المرور غير متطابقة.",
  "error_password_complexity": "يجب أن تحتوي كلمة المرور على 4 أحرف أو 4 أرقام على الأقل.",
  "error_min_age": "يجب أن يكون عمرك 18 عامًا على الأقل للتسجيل.",
  "motivationalQuote_good": "تهانينا! أنت على الطريق الصحيح!",
  "motivationalQuote_keepGoing": "استمر في التركيز، يمكنك تحقيق أهدافك اليوم!",
  "userProfileTitle": "مرحباً يا مستخدم!",
  "userProfileSubtitle": "هل أنت مستعد لهدف اليوم؟",
  "dailyProgressTitle": "التقدم اليومي",
  "todayHistoryTitle": "سجل اليوم"
};

export const hi = {
  "loginTitle": "वापसी पर स्वागत है!",
  "emailLabel": "ईमेल",
  "passwordLabel": "पासवर्ड",
  "loginButton": "लॉग इन करें",
  "noAccount": "अभी तक कोई खाता नहीं है?",
  "registerHere": "यहां रजिस्टर करें!",
  "registerTitle": "अपना खाता बनाएं",
  "nameLabel": "नाम",
  "confirmPasswordLabel": "पासवर्ड की पुष्टि कीजिये",
  "registerButton": "रजिस्टर करें",
  "profileSetupTitle": "अपनी स्वास्थ्य प्रोफ़ाइल सेट करें",
  "ageLabel": "आयु",
  "weightLabel": "वजन (किग्रा)",
  "heightLabel": "ऊंचाई (सेमी)",
  "genderLabel": "लिंग",
  "dietaryPreferencesLabel": "आहार संबंधी प्राथमिकताएं (वैकल्पिक)",
  "healthConditionsTitle": "स्वास्थ्य स्थितियाँ (सभी लागू चुनें)",
  "diabetes": "मधुमेह",
  "hypertension": "उच्च रक्तचाप",
  "cholesterol": "उच्च कोलेस्ट्रॉल / ट्राइग्लिसराइड्स",
  "obesity": "मोटापा",
  "finishButton": "समाप्त करें",
  "cameraTitle": "भोजन का विश्लेषण करें",
  "cameraInstruction": "अपने भोजन की एक तस्वीर लें",
  "cameraButton": "कैमरा",
  "galleryButton": "गैलरी",
  "settingsButton": "सेटिंग्स",
  "analysisResultTitle": "विश्लेषण परिणाम",
  "foodLabel": "भोजन",
  "nutritionalInfo": "पोषण संबंधी जानकारी",
  "calories": "कैलोरी",
  "carbs": "कार्बोहाइड्रेट",
  "sugar": "चीनी",
  "fat": "वसा",
  "sodium": "सोडियम",
  "protein": "प्रोटीन",
  "alertTitle": "स्वास्थ्य चेतावनी",
  "substitutesTitle": "विकल्प सुझाव",
  "newPhotoButton": "नई तस्वीर",
  "saveAnalysisButton": "विश्लेषण सहेजें",
  "settingsTitle": "सेटिंग्स",
  "languageLabel": "भाषा",
  "male": "पुरुष",
  "female": "महिला",
  "other": "अन्य",
  "analyzing": "आपकी तस्वीर का विश्लेषण किया जा रहा है...",
  "alert_GREEN": "अनुमत भोजन",
  "alert_YELLOW": "संयम के साथ अनुमत",
  "alert_RED": "अनुशंसित नहीं",
  "error_title": "त्रुटि",
  "error_message": "छवि का विश्लेषण नहीं किया जा सका। कृपया एक स्पष्ट तस्वीर के साथ पुनः प्रयास करें।",
  "ok": "ठीक है",
  "error_password_mismatch": "पासवर्ड मेल नहीं खाते।",
  "error_password_complexity": "पासवर्ड में कम से कम 4 अक्षर या 4 नंबर होने चाहिए।",
  "error_min_age": "पंजीकरण के लिए आपकी आयु कम से कम 18 वर्ष होनी चाहिए।",
  "motivationalQuote_good": "बधाई हो! आप सही रास्ते पर हैं!",
  "motivationalQuote_keepGoing": "ध्यान केंद्रित रखें, आप आज अपने लक्ष्य तक पहुँच सकते हैं!",
  "userProfileTitle": "नमस्ते, उपयोगकर्ता!",
  "userProfileSubtitle": "आज के लक्ष्य के लिए तैयार हैं?",
  "dailyProgressTitle": "दैनिक प्रगति",
  "todayHistoryTitle": "आज का इतिहास"
};

export const bn = {
  "loginTitle": "আবারো স্বাগতম!",
  "emailLabel": "ইমেল",
  "passwordLabel": "পাসওয়ার্ড",
  "loginButton": "লগইন করুন",
  "noAccount": "এখনও কোনো একাউন্ট নেই?",
  "registerHere": "এখানে নিবন্ধন করুন!",
  "registerTitle": "আপনার অ্যাকাউন্ট তৈরি করুন",
  "nameLabel": "নাম",
  "confirmPasswordLabel": "পাসওয়ার্ড নিশ্চিত করুন",
  "registerButton": "নিবন্ধন করুন",
  "profileSetupTitle": "আপনার স্বাস্থ্য প্রোফাইল সেট আপ করুন",
  "ageLabel": "বয়স",
  "weightLabel": "ওজন (কেজি)",
  "heightLabel": "উচ্চতা (সেমি)",
  "genderLabel": "লিঙ্গ",
  "dietaryPreferencesLabel": "খাদ্য পছন্দ (ঐচ্ছিক)",
  "healthConditionsTitle": "স্বাস্থ্য অবস্থা (প্রযোজ্য সব নির্বাচন করুন)",
  "diabetes": "ডায়াবেটিস",
  "hypertension": "উচ্চ রক্তচাপ",
  "cholesterol": "উচ্চ কোলেস্টেরল / ট্রাইগ্লিসারাইড",
  "obesity": "স্থূলতা",
  "finishButton": "শেষ করুন",
  "cameraTitle": "খাবার বিশ্লেষণ করুন",
  "cameraInstruction": "আপনার খাবারের একটি ছবি তুলুন",
  "cameraButton": "ক্যামেরা",
  "galleryButton": "গ্যালারি",
  "settingsButton": "সেটিংস",
  "analysisResultTitle": "বিশ্লেষণ ফলাফল",
  "foodLabel": "খাবার",
  "nutritionalInfo": "পুষ্টি সম্পর্কিত তথ্য",
  "calories": "ক্যালোরি",
  "carbs": "কার্বোহাইড্রেট",
  "sugar": "চিনি",
  "fat": "চর্বি",
  "sodium": "সোডিয়াম",
  "protein": "প্রোটিন",
  "alertTitle": "স্বাস্থ্য সতর্কতা",
  "substitutesTitle": "বিকল্প পরামর্শ",
  "newPhotoButton": "নতুন ছবি",
  "saveAnalysisButton": "বিশ্লেষণ সংরক্ষণ করুন",
  "settingsTitle": "সেটিংস",
  "languageLabel": "ভাষা",
  "male": "পুরুষ",
  "female": "মহিলা",
  "other": "অন্যান্য",
  "analyzing": "আপনার ছবি বিশ্লেষণ করা হচ্ছে...",
  "alert_GREEN": "অনুমোদিত খাবার",
  "alert_YELLOW": "পরিমিতভাবে অনুমোদিত",
  "alert_RED": "সুপারিশ করা হয় না",
  "error_title": "ত্রুটি",
  "error_message": "ছবি বিশ্লেষণ করা যায়নি। অনুগ্রহ করে একটি পরিষ্কার ছবি দিয়ে আবার চেষ্টা করুন।",
  "ok": "ঠিক আছে",
  "error_password_mismatch": "পাসওয়ার্ড মেলে না।",
  "error_password_complexity": "পাসওয়ার্ডে কমপক্ষে ৪টি অক্ষর বা ৪টি সংখ্যা থাকতে হবে।",
  "error_min_age": "নিবন্ধন করার জন্য আপনার বয়স কমপক্ষে ১৮ বছর হতে হবে।",
  "motivationalQuote_good": "অভিনন্দন! আপনি সঠিক পথে আছেন!",
  "motivationalQuote_keepGoing": "মনোযোগ ধরে রাখুন, আপনি আজ আপনার লক্ষ্যে পৌঁছাতে পারবেন!",
  "userProfileTitle": "হ্যালো, ব্যবহারকারী!",
  "userProfileSubtitle": "আজকের লক্ষ্যের জন্য প্রস্তুত?",
  "dailyProgressTitle": "দৈনিক অগ্রগতি",
  "todayHistoryTitle": "আজকের ইতিহাস"
};

export const ru = {
  "loginTitle": "С возвращением!",
  "emailLabel": "Электронная почта",
  "passwordLabel": "Пароль",
  "loginButton": "Войти",
  "noAccount": "Еще нет аккаунта?",
  "registerHere": "Зарегистрируйтесь здесь!",
  "registerTitle": "Создайте свой аккаунт",
  "nameLabel": "Имя",
  "confirmPasswordLabel": "Подтвердите пароль",
  "registerButton": "Зарегистрироваться",
  "profileSetupTitle": "Настройте свой профиль здоровья",
  "ageLabel": "Возраст",
  "weightLabel": "Вес (кг)",
  "heightLabel": "Рост (см)",
  "genderLabel": "Пол",
  "dietaryPreferencesLabel": "Предпочтения в еде (необязательно)",
  "healthConditionsTitle": "Состояния здоровья (выберите все, что применимо)",
  "diabetes": "Диабет",
  "hypertension": "Гипертония",
  "cholesterol": "Высокий холестерин / Триглицериды",
  "obesity": "Ожирение",
  "finishButton": "Завершить",
  "cameraTitle": "Анализ еды",
  "cameraInstruction": "Сфотографируйте свою еду",
  "cameraButton": "Камера",
  "galleryButton": "Галерея",
  "settingsButton": "Настройки",
  "analysisResultTitle": "Результат анализа",
  "foodLabel": "Еда",
  "nutritionalInfo": "Пищевая ценность",
  "calories": "Калории",
  "carbs": "Углеводы",
  "sugar": "Сахар",
  "fat": "Жиры",
  "sodium": "Натрий",
  "protein": "Белки",
  "alertTitle": "Оповещение о здоровье",
  "substitutesTitle": "Предложения по замене",
  "newPhotoButton": "Новое фото",
  "saveAnalysisButton": "Сохранить анализ",
  "settingsTitle": "Настройки",
  "languageLabel": "Язык",
  "male": "Мужской",
  "female": "Женский",
  "other": "Другой",
  "analyzing": "Анализ вашей фотографии...",
  "alert_GREEN": "Разрешенная еда",
  "alert_YELLOW": "Разрешено в умеренных количествах",
  "alert_RED": "Не рекомендуется",
  "error_title": "Ошибка",
  "error_message": "Не удалось проанализировать изображение. Пожалуйста, попробуйте еще раз с более четкой фотографией.",
  "ok": "ОК",
  "error_password_mismatch": "Пароли не совпадают.",
  "error_password_complexity": "Пароль должен содержать не менее 4 букв или 4 цифр.",
  "error_min_age": "Вам должно быть не менее 18 лет для регистрации.",
  "motivationalQuote_good": "Поздравляем! Вы на правильном пути!",
  "motivationalQuote_keepGoing": "Продолжайте фокусироваться, вы можете достичь своих целей сегодня!",
  "userProfileTitle": "Здравствуйте, Пользователь!",
  "userProfileSubtitle": "Готовы к сегодняшней цели?",
  "dailyProgressTitle": "Ежедневный прогресс",
  "todayHistoryTitle": "История за сегодня"
};
